# Generated by Django 5.1.4 on 2025-01-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='รูปภาพ')),
                ('is_active', models.BooleanField(default=True, verbose_name='แสดงผล')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อคอร์สเรียน')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('instructor', models.CharField(max_length=255, verbose_name='ผู้สอน')),
                ('duration', models.CharField(max_length=50, verbose_name='ระยะเวลา')),
                ('image', models.ImageField(upload_to='booking_courses/', verbose_name='รูปปกคอร์ส')),
                ('payment_qr', models.ImageField(blank=True, null=True, upload_to='payment_qrs/', verbose_name='QR Code การชำระเงิน')),
                ('status', models.CharField(choices=[('pending', 'รอการตรวจสอบ'), ('approved', 'อนุมัติแล้ว'), ('revision', 'ส่งกลับไปแก้ไข')], default='pending', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ส่งคอร์ส')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='courses/images/')),
                ('instructor', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'รอการอนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('revision', 'ส่งกลับมาแก้ไข'), ('revised', 'แก้ไขแล้วรอการตรวจสอบ')], default='pending', max_length=10)),
                ('revision_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='ชื่อคอร์ส')),
                ('customer_name', models.CharField(max_length=255, verbose_name='ชื่อลูกค้า')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมลลูกค้า')),
                ('transfer_slip', models.ImageField(upload_to='transfer_slips/', verbose_name='สลิปการโอน')),
                ('status', models.CharField(choices=[('paid', 'จ่ายแล้ว'), ('pending', 'รอการตรวจสอบ')], default='pending', max_length=50, verbose_name='สถานะ')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='เวลาการจอง')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='staff_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('member', 'Member'), ('teacher', 'Teacher')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'รอการตรวจสอบ'), ('approved', 'อนุมัติแล้ว'), ('revision', 'ส่งกลับไปแก้ไข'), ('revised', 'แก้ไขแล้วรอการตรวจสอบ')], default='pending', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('extra_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='course_images/')),
                ('extra_image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อคอร์ส')),
                ('description', models.TextField(verbose_name='คำอธิบาย')),
                ('video_url', models.URLField(verbose_name='ลิงก์วิดีโอ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('duration', models.CharField(max_length=50, verbose_name='ระยะเวลา')),
                ('instructor', models.CharField(max_length=255, verbose_name='ผู้สอน')),
                ('is_approved', models.BooleanField(default=False, verbose_name='ตรวจสอบแล้ว')),
                ('status', models.CharField(choices=[('pending', 'รอการตรวจสอบ'), ('approved', 'อนุมัติแล้ว'), ('revision', 'ส่งกลับไปแก้ไข')], default='pending', max_length=10, verbose_name='สถานะ')),
                ('payment_qr', models.ImageField(blank=True, null=True, upload_to='payment_qrs/', verbose_name='QR Code การชำระเงิน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('additional_description', models.TextField()),
                ('image', models.ImageField(upload_to='course_images/')),
                ('additional_image', models.ImageField(upload_to='course_additional_images/')),
                ('extra_image_1', models.ImageField(blank=True, null=True, upload_to='course_extra_images/')),
                ('extra_image_2', models.ImageField(blank=True, null=True, upload_to='course_extra_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
        ),
    ]
