# Generated by Django 5.1.4 on 2025-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_banner_is_active_banner_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_name_en', models.CharField(max_length=255)),
                ('nickname_th', models.CharField(max_length=50)),
                ('nickname_en', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(choices=[('อนุบาล 2', 'อนุบาล 2'), ('อนุบาล 3', 'อนุบาล 3'), ('ประถมศึกษาปีที่ 1', 'ประถมศึกษาปีที่ 1'), ('ประถมศึกษาปีที่ 2', 'ประถมศึกษาปีที่ 2'), ('ประถมศึกษาปีที่ 3', 'ประถมศึกษาปีที่ 3'), ('ประถมศึกษาปีที่ 4', 'ประถมศึกษาปีที่ 4'), ('ประถมศึกษาปีที่ 5', 'ประถมศึกษาปีที่ 5'), ('ประถมศึกษาปีที่ 6', 'ประถมศึกษาปีที่ 6'), ('อื่นๆ', 'อื่นๆ')], max_length=30)),
                ('other_grade', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_nickname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('line_id', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(choices=[('K1', 'K1'), ('K2-3', 'K2-3'), ('P1-3', 'P1-3'), ('P4-6', 'P4-6')], max_length=50)),
                ('payment_slip', models.ImageField(blank=True, null=True, upload_to='payment_slips/')),
                ('payment_status', models.CharField(choices=[('pending', 'รอการตรวจสอบ'), ('approved', 'ชำระแล้ว'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=20)),
                ('booking_status', models.CharField(choices=[('pending', 'รอการยืนยัน'), ('confirmed', 'ยืนยันแล้ว'), ('canceled', 'ยกเลิก')], default='pending', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qrs/'),
        ),
    ]
