# Generated by Django 5.1.4 on 2025-02-02 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_coursebooking_course_payment_qr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingCourse',
        ),
        migrations.AlterField(
            model_name='coursebooking',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
