# Generated by Django 5.1.4 on 2025-02-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_delete_bookingcourse_alter_coursebooking_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebooking',
            name='selected_course',
            field=models.CharField(choices=[('K1', 'K1 = 9:00 - 10:00'), ('K2-3', 'K2-3 = 10:30 - 11:30'), ('P1-3', 'P1-3 = 10:30 - 11:30'), ('P4-6', 'P4-6 = 10:30 - 11:30')], default='K1', max_length=50),
        ),
    ]
