# Generated by Django 5.1.4 on 2025-02-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_coursebooking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
