# Generated by Django 5.1.4 on 2025-03-10 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_videolesson_video_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='หัวข้อรายละเอียด')),
                ('description', models.TextField(verbose_name='คำอธิบาย')),
                ('additional_description', models.TextField(verbose_name='รายละเอียดเพิ่มเติม')),
                ('image', models.ImageField(upload_to='videocourse_details/images/', verbose_name='รูปภาพหลักของรายละเอียด')),
                ('additional_image', models.ImageField(blank=True, null=True, upload_to='videocourse_details/extra_images/', verbose_name='รูปภาพเพิ่มเติม 1')),
                ('extra_image_1', models.ImageField(blank=True, null=True, upload_to='videocourse_details/extra_images/', verbose_name='รูปภาพเพิ่มเติม 2')),
                ('extra_image_2', models.ImageField(blank=True, null=True, upload_to='videocourse_details/extra_images/', verbose_name='รูปภาพเพิ่มเติม 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
            ],
        ),
        migrations.DeleteModel(
            name='VideoCourseDetail',
        ),
        migrations.RemoveField(
            model_name='videocourse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='videocourse',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='name',
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='payment_qr',
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='price',
        ),
        migrations.AddField(
            model_name='videocourse',
            name='image',
            field=models.ImageField(default='default_course_image.jpg', upload_to='video_courses/images/'),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='instructor',
            field=models.CharField(default='ไม่ระบุผู้สอน', max_length=255),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='videocourses/payment_qrs/', verbose_name='QR Code การชำระเงิน'),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='revision_message',
            field=models.TextField(blank=True, null=True, verbose_name='ข้อความการแก้ไข'),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='title',
            field=models.CharField(default='ไม่มีชื่อคอร์ส', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.videocourse'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='title',
            field=models.CharField(default='ไม่มีชื่อบทเรียน', max_length=255, verbose_name='ชื่อวิดีโอ'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='description',
            field=models.TextField(verbose_name='คำอธิบาย'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='status',
            field=models.CharField(choices=[('pending', 'รอการอนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('revision', 'ส่งกลับไปแก้ไข'), ('revised', 'แก้ไขแล้วรอการตรวจสอบ')], default='pending', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สอน'),
        ),
        migrations.AddField(
            model_name='videocoursedetails',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.videocourse', verbose_name='คอร์สที่เกี่ยวข้อง'),
        ),
    ]
