# Generated by Django 5.1.4 on 2025-03-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_videocourse_added_by_videocourse_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocoursedetails',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='videocourse_details/previews/', verbose_name='วิดีโอตัวอย่าง'),
        ),
    ]
