# Generated by Django 5.1.4 on 2025-03-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_videocoursedetails_preview_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocoursedetails',
            name='extra_image_1',
        ),
        migrations.RemoveField(
            model_name='videocoursedetails',
            name='extra_image_2',
        ),
        migrations.AddField(
            model_name='videolesson',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='lesson_documents/', verbose_name='เอกสารประกอบการเรียน'),
        ),
    ]
