# Generated by Django 5.1.4 on 2025-03-10 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_videocoursedetails_extra_image_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCourseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_slip', models.ImageField(upload_to='payment_slips/', verbose_name='สลิปการโอนเงิน')),
                ('payment_status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('confirmed', 'ชำระแล้ว'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=10, verbose_name='สถานะการชำระเงิน')),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่รายการโอนเงิน')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ชำระเงิน')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.videocourse', verbose_name='คอร์สที่ซื้อ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ซื้อ')),
            ],
        ),
    ]
